name = "alg_tk"
uuid = "70afd6a5-1acf-4b53-88b6-7a68762e86fa"
authors = ["Jacob Purcell <japurc@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
